name: Build and deploy Node.js app to Azure Web App - wasel-tasel-backend

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      # 1. Checkout the repo
      - uses: actions/checkout@v4

      # 2. Setup Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22.x'

      # 3. Install dependencies, build, and test
      - name: Install dependencies, build, and test
        run: |
          cd backend
          npm install
          npm run build --if-present
          npm run test --if-present

      # 4. Upload backend folder as artifact
      - name: Upload backend artifact
        uses: actions/upload-artifact@v4
        with:
          name: backend-artifact
          path: ./backend

  deploy:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      id-token: write
      contents: read

    steps:
      # 1. Download the artifact
      - name: Download backend artifact
        uses: actions/download-artifact@v4
        with:
          name: backend-artifact

      # 2. Login to Azure
      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_D1718F243250431688CE0B5DD01751C8 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_3BA48FAA1462469A94049CD72DBB67F0 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_EE7A2B631FDC466DA550E0286937E6C2 }}

      # 3. Deploy to Azure Web App
      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'wasel-tasel-backend'
          slot-name: 'Production'
          package: ./backend-artifact   # ← المسار الصحيح بعد تنزيل الـ artifact
